--- 
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: proxy
  become: true
  roles:
    - proxy_nginx
  vars:
    target_server: "{{ groups['nginx'] | first }}" 
