---
# tasks file for nginx_custom
- name: Установка Nginx 
  apt:
    name: "nginx"
    state: present

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'nginx' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_1
  notify: "Nginx Reloader"